config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'project_manager#index', as: 'project_manager'

  resources 'projects', :only => [:new, :create]

  resources :categories do
    resources :projects
  end

  resources :comments
  resources :tasks

  resources :tasks do
    member do
      get :completed
      put :completed
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  has_many :project_categories
  has_many :categories, through: :project_categories

  validates_uniqueness_of :title
  # validates_uniqueness_of :description

  validates_presence_of :title, :description
  validates_presence_of :category_ids, message: 'A category must be present'

  # accepts_nested_attributes_for :categories, :reject_if => proc { |attrs| attrs['title'].blank? }

  def categories_attributes=(categories_attributes)
    categories_attributes.values.each do |category_attribute|
      category = Category.find_or_create_by(category_attribute)
      if category.title?
        categories << category
      elsif category.persisted?
        category.destroy
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def new
    @project = Project.new
    if Category.find_by(id: params[:category_id]) != nil
      @category = Category.find_by(id: params[:category_id])
      @category = @category.id
    else
      @category = []
  end
    # @project.categories.build
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:error] = 'You have successfully deleted this project.'
    redirect_to project_manager_path
  end

  def create
    @project = Project.create(project_params)
    @project.user_id = current_user.id
    if @project.save
      flash[:notice] = 'Project successfully created'
      redirect_to category_project_path(ProjectCategory.limit(1).where(project_id: [@project]).pluck(:category_id), @project)
    else
      flash[:alert] = 'Project could not be created'
      render 'new'
    end
  end

  def show
    # @project = Project.find(params[:id])
    if params[:category_id]
      @category = Category.find_by(id: params[:category_id])
      @project = @category.projects.find_by(id: params[:id])
      if @project.nil?
        redirect_to category_projects(@project), alert: 'Project not found'
      end
    else
      @project = Project.find(params[:id])
    end

    @user = User.find(@project.user_id).full_name
    @comment = Comment.new
    @comments = Comment.filter_comments(@project.id)
    @task = Task.new
    @tasks = Task.filter_tasks(@project.id)
  end

  def index
    @projects = Project.all
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :task_id, :category_id, category_ids: [], categories_attributes: [:title])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<h2> Create a Project </h2>
<%= form_for @project do |f| %>

<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <h3>Categories</h3>
<% if Category.count == 0 %>
  No categories to show<br><br>
<% else %>
  <div class="field">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :title, :checked => [@category] %><br>
<% end %>
  <br>Create new category:
  <%= f.fields_for :categories, @project.categories.build do |categories_fields| %>
        <%= categories_fields.text_field :title %>
<% end %>
  <div class="field">
    Title: <%= f.text_field :title %><br>
    Description: <br> <%= f.text_area :description, cols: 50, rows: 8 %><br>
  </div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/projects/new.html.erb
<%= render partial: 'projects/form', locals: { project: @project } %>

app/views/projects/show.html.erb
<h2>Project: <%= @project.title %></h2>
<% if current_user.present? && current_user.id == @project.user_id %>
  <%= link_to 'Delete Project', category_project_path(@category.id, @project.id), :method => :delete %>
<% end %>
<h3>Description: <%= @project.description %></h3>
Posted By: <%= @user %><br><br>
<h4>Tasks:</h4>
<% @tasks.each_with_index do |task, index| %>
  <%= index+1 %>: <%= task.task %> <% if current_user.present? %> -
    <% if task.completed != true %>
      <%= link_to "Mark Completed", {:controller => "tasks", :action => "completed", :id => task.id, :category_id => @category.id, :project_id => @project.id} %>
    <% else %>
      <b>Completed</b>
    <% end %>
  <% end %>
  <br><br>
<% end %>

<% if current_user.present? %>
<h4> Add a Task: </h4>
<%= render partial: 'tasks/form', locals: { task: @task } %>
<% end %>

<hr>
<h4>Comments:</h4></br>
<% @comments.each_with_index do |comment, index| %>
  <%= index+1 %>: <%= comment.comment %> - <%= comment.get_name_from_user_id(comment.user_id) %>

  <%if current_user.present? && current_user.id == comment.user_id %>
  <%= link_to 'Delete', comment_path(comment.id, :project_id => @project.id, :category_id => @category.id), :method => :delete %>
  <% end %>

<br><br>
<% end %>
<% if current_user.present? %>

<h4>Add a Comment:</h4>
<%= render partial: 'comments/form', locals: { comment: @comment } %>
<% end %>