config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'project_manager#index', as: 'project_manager'

  resources 'projects', :only => [:new, :create]

  resources :categories do
    resources :projects
  end

  resources :comments
  resources :tasks

  resources :tasks do
    member do
      get :completed
      put :completed
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :project_categories
  has_many :projects, through: :project_categories

  validates_uniqueness_of :title
  validates_presence_of :title
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @project = Project.new
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category successfully created'
      redirect_to category_path(@category)
    else
      flash[:alert] = 'Category could not be created'
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <%= f.text_field :title %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<ul>
<% @categories.each do |category| %>
<li><%= category.title %></li>
<% end %>
</ul>

app/views/categories/new.html.erb
<h2> Create Category </h2>
<%= render partial: 'form', locals: { category: @category } %>

app/views/categories/show.html.erb
<h2> Category: <%= @category.title %> </h2>
<% if @category.projects.count == 0 %>
  <p> There are currently no projects here.</p>
  <% if current_user.present? %><br>
    <h3><%= link_to "Create a Project", new_category_project_path(@category.id) %></h3>
  <% end %>
<% else %>
  <h3> Projects: </h3>
  <ul>
  <% @category.projects.each do |project| %>
    <li><%= link_to project.title, category_project_path(@category.id, project) %></li>
  <% end %>
  </ul>
  <% if current_user.present? %><br>
    <h3><%= link_to "Create a Project", new_category_project_path(@category.id) %></h3>
  <% end %>
<% end %>