config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'project_manager#index', as: 'project_manager'

  resources 'projects', :only => [:new, :create]

  resources :categories do
    resources :projects
  end

  resources :comments
  resources :tasks

  resources :tasks do
    member do
      get :completed
      put :completed
    end
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <ul class="nav navbar-nav">
        <li> <%= link_to "Projects Home", project_manager_path %> </li>
        <% if !user_signed_in? %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Create a Category", new_category_path %></li>
          <li><%= link_to "Create a Project", new_project_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
        <% end %>
    </ul>

    <% if user_signed_in? %>
     <p class="navbar-text navbar-right" style ="margin-right: 15px;">Signed in as <%= link_to current_user.full_name, edit_user_registration_path %> (<%= link_to current_user.email, edit_user_registration_path %>)</b></p>
     <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <%= content_tag(:div, flash[:error], :class => "alert alert-warning") if flash[:error] %>
      <%= content_tag(:div, flash[:notice], :class => "alert alert-success") if flash[:notice] %>
      <%= content_tag(:div, flash[:alert], :class => "alert alert-danger") if flash[:alert] %>
      <div class="col-md-1"></div>
      <div class="col-md-10">
        <div class="jumbotron"><%= yield %>
        </div>
      </div>
      <div class="col-md-1"></div>
    </div>
  </div>

</body>
</html>